# Change these first
owner: Smirf123 # Your GitHub organization or username, where this repository lives
repo: Kekmart-Uptime-Monitor # The name of this repository

sites:
  - name: Kmart Bot
    url: https://kekmart.smirf123.dev/kekbot/status
    expectedStatusCodes:
      - 200
      - 201
      - 418
  - name: VRCKmart
    url: https://vrckmart.com
  - name: Discord
    url: https://discord.gg/kmart
  - name: Kmart Express
    url: https://kekmart.smirf123.dev/kekbot/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: kmartstatus.smirf123.dev
  # baseUrl: /your-repo-name
  logoUrl: https://media.discordapp.net/attachments/914574247819608065/1255543427756462090/kmart_icon.png?ex=66eaeff0&is=66e99e70&hm=9bdf55b54ff6a80cd475f27a73b56d182fcb2429c1cdc88729300f432cde923d&
  name: VRChat Kmart
  introTitle: "**Kmart** How did I get this disease, what are my treatment options."
  introMessage: How does this affect my loved ones
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
